/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.java.application;


import java.util.Arrays;
import java.io.IOException;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.apache.commons.cli.DefaultParser;

import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;

public class App {
	
	private static final boolean DEBUG = true;
	
    private static final Logger LOGGER = Logger.getLogger(App.class.getName());
    /*
     * Log4j Level	JUL Level
TRACE	FINEST
DEBUG	FINE
INFO	INFO
WARN	WARNING
ERROR	SEVERE
FATAL	SEVERE (no direct equivalent in JUL)

     */
	// private static Logger LOGGER = LogManager.getLogger(App.class);
	
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        try {
            // Load the logging properties from the classpath (resources folder)
            LogManager.getLogManager().readConfiguration(App.class.getClassLoader().getResourceAsStream("my-app-logging.properties"));
        } catch (IOException e) {
            System.err.println("Could not load logging configuration: " + e.getMessage());
        }

        //only the one of these will work, I think we shoul not combine the logging.properties with the 
        //programmatical configuration 

        try {

            FileHandler fileHandler = new FileHandler("myapp-handler-from-code.log", 50000, 5, true);
            fileHandler.setFormatter(new SimpleFormatter());
            fileHandler.setLevel(Level.FINE);
            LOGGER.addHandler(fileHandler);
        } catch (IOException e) {
            e.printStackTrace();
        }

        LOGGER.fine(new App().getGreeting());
        LOGGER.info("info level message");
        LOGGER.warning("warn level message");
        LOGGER.severe("error level message");
        
        if (DEBUG) {
        	
			LOGGER.fine("Given args: " + Arrays.toString(args));
		}
        
        
        final Options options = new Options();

        options.addOption("i", "input-file", true, "Input file, REQUIRED");
        options.addOption("o", "output-file", true, "Output file, REQUIRED");

        final org.apache.commons.cli.CommandLineParser parser = new DefaultParser();

        try {
            final CommandLine cmd = parser.parse(options, args);

            Option[] allOptions = cmd.getOptions();

            final boolean inputON = cmd.hasOption("i");
            final boolean outputON = cmd.hasOption("o");
            
            if (inputON && outputON) {
            	LOGGER.info("Provided correct arguments");
            	final String inputFile = cmd.getOptionValue("i");
            	final String outputFile = cmd.getOptionValue("o");
            	
            	LOGGER.fine("inputFile: " + inputFile);
            	LOGGER.fine("outputFile: " + outputFile);
            	
            	
            } else {
            	printUsage(options);
            }
            
        } catch (final org.apache.commons.cli.MissingArgumentException e) {
            LOGGER.severe("INVALID PARAMS");
            printUsage(options);
            e.printStackTrace();
        } catch (final ParseException e) {
            e.printStackTrace();
        }
        
        
    }
    
    private static void printUsage(final Options options) {
        final HelpFormatter formatter = new HelpFormatter();
        final StringBuilder usageSb = new StringBuilder();

        usageSb.append("\nbash app/build/install/my-java-application/bin/my-java-application \\\n" +
                " -i <input file> \\\n" +
                " -o <output file> ");

        final StringBuilder header = new StringBuilder();
        header.append("\nmy-java-application\n");
        header.append("\nThis is just demo application. ");
        header.append("\nExample:");
        header.append("\nbash app/build/install/my-java-application/bin/my-java-application \\\n" +
                " -i inputfile.txt  \\\n" +
                " -o outputfile.txt ");
        header.append("\n\n");
        header.append("\nOptions:\n");
        formatter.printHelp(usageSb.toString(), header.toString(), options,
                "\nFor more information please check README.md file or \ncontact author\n\n");
    }
    
    
}
